apiVersion: batch/v1
kind: CronJob
metadata:
  name: parlameter-update-flow
spec:
  schedule: "0 2,8,14,20 * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        spec:
          containers:
          - name: run-parser-flow
            image: parlaparser-slovenija
            env:
              - name: DJANGO_SETTINGS_MODULE
                value: parladata_project.settings.k8s
              - name: PARSER_MANDATE_START_DATE
                value: '2018-06-22'
              - name: PARSER_MAIN_ORG_ID
                value: '137'
              - name: PARSER_MANDATE_ID
                value: '2'
              - name: INSTALATION_NAME
                value: Slovenija
              - name: PARSER_INTERVAL_HOURS
                value: '6'
            envFrom:
              - secretRef:
                  name: parladata-slovenija-credentials
              - secretRef:
                  name: parlaparser-slovenija-credentials
            resources:
              requests:
                memory: 6Gi # OOMKilled + classla lemmatizer
                cpu: 600m
              limits:
                memory: 10Gi # OOMKilled + classla lemmatizer
                cpu: 2000m
          restartPolicy: Never
