apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: parlameter-slovenija
resources:
  - cronjob.yaml
images:
  - name: parlaparser-slovenija
    newName: rg.fr-par.scw.cloud/djnd/parlaparser-slovenija
    newTag: '7e9b02c2c9182f7dd4a5522eacbc76ef38e0f809'
