apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: parlameter-slovenija
resources:
  - cronjob.yaml
images:
  - name: parlaparser-slovenija
    newName: rg.fr-par.scw.cloud/djnd/parlaparser-slovenija
    newTag: 'b86d246143b80444382e88d60ad83b687277a91e'
