apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: parlameter-slovenija
resources:
  - cronjob.yaml
images:
  - name: parlaparser-slovenija
    newName: rg.fr-par.scw.cloud/djnd/parlaparser-slovenija
    newTag: 'c58fddd5c7f1e24bcbd1574f4d9668b05ec804bc'
